cart/urls.py
from django.urls import path
from . import views

from django.urls import re_path
from . import views
app_name = 'cart'
urlpatterns = [
    re_path(r'^$', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

honeymelon_production/urls.py
from django import views
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include


urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('allauth.urls')),

    # здесь делаем только перенаправление на файл url.py приложения
    path('cart/', include("cart.urls")),#если поставить на строку ниже то корзина не будет работать
    path('', include("catalog.urls")),#LOGIN_REDIRECT_URL = 'blog-home' в settings.py (возможно переделать индексную страницу) name='index-home'
    path('orders/',include("orders.urls", namespace="orders")),
    path('catalog/', include("catalog.urls")),#, namespace="catalog"
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns = [
    path('create_order/', views.order_product, name='order_create'), 
    ]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from  django import forms
 
PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 2)]
 
 
class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int, label='Количество')
    update = forms.BooleanField(required=False, initial=True,
                                widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import redirect, get_object_or_404, render
from django.views.decorators.http import require_POST
 
from catalog.models import Product
from .cart import Cart
from .forms import CartAddProductForm
# Create your views here.
@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends "catalog/base.html" %}
{% load static %}
 
{% block title %}
    Корзина товаров
{% endblock %}
 
{% block content %}



    
    

    <div class="modal">
        <header class="header-catalog">
            {% block navigation %}
            {% include 'catalog/navbar.html' %}
            {% endblock %}
            </header>
            <div class="container">
            <h2 class="title-1">Твоя корзина</h2>
            <div class="micro_navbar">
                <a href="/catalog/catalog-list/"><button class="detail_catalog">Вернуться в каталог</button></a>
            </div>
        
        <div class="modal-content">
            {% for item in cart %}
            {% with product=item.product %}
            <div class="product-favorites">
                <a href="{{ product.get_absolute_url }}">
                    <img src="
                            {% if product.image %}{{ product.image.url }}{% endif %}">
                </a>
                <h3>{{ product.name }}</h3>
                <p class="price-favorites">{{ item.price }} р.</p>
                <a href="{% url 'cart:cart_remove' product.id %}">Удалить</a>
                <td>
                    <form action="{% url 'cart:cart_add' product.id %}"
                          method="post">
                        {{ item.update_quantity_form.quantity }}
                        {{ item.update_quantity_form.update }}
                        
                        {% csrf_token %}
                    </form>
                </td>
            </div>
            {% endwith %}
        {% endfor %}

        <td class="num">Итого: {{ cart.get_total_price }} р.</td>
        <a href="{% url 'orders:order_create' %}" ><button class="close">Заказ</button></a>
        </div>
    </div>
</div>
{% endblock %} 